[jenkins]
jenkins_server ansible_host=13.207.70.94 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/project-key.pem ansible_python_interpreter=/usr/bin/python3

[app_servers]
app_server ansible_host=<APP_PUBLIC_IP> ansible_user=ubuntu ansible_ssh_private_key_file=/var/lib/jenkins/.ssh/project-key.pem ansible_python_interpreter=/usr/bin/python3

[all:vars]
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
